image: node:20

stages:
  - test
  
javascript:
  stage: test
  script:
    - npm ci # like npm install, but faster (requires package-lock.json)
#    - npm run build -- we use ts-jest, no need for compilation
    - npm test -- --runInBand
  coverage: '/^All files\s*\|\s*([0-9.]+)\s*\|.*/'
  artifacts:
    reports:
      junit:
        - junit.xml